Repository wobgob/azerothcore-wotlk, pull requests merged in 2021-09, with the labels that each got.

#31 Workflows
  .github/workflows/build.yml
  .github/workflows/check_pending_sql.yml
  .github/workflows/codestyle.yml
  .github/workflows/core_build.yml
  .github/workflows/docker_build.yml
  .github/workflows/import_pending.yml
  .github/workflows/issue-labeler.yml
  .github/workflows/labeler.yml
  .github/workflows/macos_build.yml
  .github/workflows/windows_build.yml
  apps/ci/ci-worldserver-dry-run.sh
  modules/mod-loot-box/conf/LootBox.conf.dist
Labels: Bash, Workflow

#34 fix: Defensive scaling in 40 mans
  .github/workflows/wobgob_build.yml
  apps/ci/ci-worldserver-dry-run.sh
  modules/mod-player-settings/src/PlayerSettings.cpp
Labels: Bash, Workflow

#37 Track resources
  modules/mod-loot-box/src/LootBoxPlayer.cpp
  modules/mod-player-settings/src/PlayerSettings.cpp
  src/server/game/Handlers/SpellHandler.cpp
  src/server/game/Spells/Auras/SpellAuras.cpp
Labels: CORE

#38 feat: Solo LFG module
  modules/mod-solo-lfg/.editorconfig
  modules/mod-solo-lfg/.git_commit_template.txt
  modules/mod-solo-lfg/.gitattributes
  modules/mod-solo-lfg/.gitignore
  modules/mod-solo-lfg/CMakeLists.txt
  modules/mod-solo-lfg/LICENSE
  modules/mod-solo-lfg/README.md
  modules/mod-solo-lfg/conf/SoloLfg.conf.dist
  modules/mod-solo-lfg/include.sh
  modules/mod-solo-lfg/setup_git_commit_template.sh
  modules/mod-solo-lfg/src/Lfg_Solo.cpp
  modules/mod-solo-lfg/src/loader.h
  src/server/game/DungeonFinding/LFGMgr.cpp
  src/server/game/DungeonFinding/LFGMgr.h
  src/server/game/DungeonFinding/LFGQueue.cpp
Labels: Bash, CORE

#36 Loot Boxes on Milestone Levels
  modules/mod-level-up/.editorconfig
  modules/mod-level-up/.git_commit_template.txt
  modules/mod-level-up/.gitattributes
  modules/mod-level-up/.github/workflows/core-build.yml
  modules/mod-level-up/.gitignore
  modules/mod-level-up/.vscode/settings.json
  modules/mod-level-up/CMakeLists.txt
  modules/mod-level-up/LICENSE
  modules/mod-level-up/README.md
  modules/mod-level-up/conf/LevelUp.conf.dist
  modules/mod-level-up/conf/conf.sh.dist
  modules/mod-level-up/include.sh
  modules/mod-level-up/setup_git_commit_template.sh
  modules/mod-level-up/sql/README.md
  modules/mod-level-up/sql/auth/updates/.gitkeep
  modules/mod-level-up/sql/characters/updates/.gitkeep
  modules/mod-level-up/sql/world/base/data.sql
  modules/mod-level-up/sql/world/updates/.gitkeep
  modules/mod-level-up/src/LevelUpPlayer.cpp
  modules/mod-level-up/src/LevelUp_loader.h
Labels: Bash
